// <auto-generated />
using HomeSecuritySystem.Persistence.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeSecuritySystem.Persistence.Migrations
{
    [DbContext(typeof(HSSDatabaseContext))]
    [Migration("20250201215245_IntiMigration")]
    partial class IntiMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeSecuritySystem.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("HomeSecuritySystem.Domain.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1234 Main St",
                            City = "City",
                            Country = "Country",
                            Name = "House 1",
                            PostalCode = 12345,
                            Region = "Region"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1234 Main St",
                            City = "City",
                            Country = "Country",
                            Name = "House 2",
                            PostalCode = 12345,
                            Region = "Region"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1234 Main St",
                            City = "City",
                            Country = "Country",
                            Name = "House 3",
                            PostalCode = 12345,
                            Region = "Region"
                        },
                        new
                        {
                            Id = 4,
                            Address = "1234 Main St",
                            City = "City",
                            Country = "Country",
                            Name = "House 4",
                            PostalCode = 12345,
                            Region = "Region"
                        },
                        new
                        {
                            Id = 5,
                            Address = "1234 Main St",
                            City = "City",
                            Country = "Country",
                            Name = "House 5",
                            PostalCode = 12345,
                            Region = "Region"
                        });
                });

            modelBuilder.Entity("HomeSecuritySystem.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HomeSecuritySystem.Domain.Device", b =>
                {
                    b.HasOne("HomeSecuritySystem.Domain.House", null)
                        .WithMany("Devices")
                        .HasForeignKey("HouseId");
                });

            modelBuilder.Entity("HomeSecuritySystem.Domain.User", b =>
                {
                    b.HasOne("HomeSecuritySystem.Domain.House", null)
                        .WithMany("Users")
                        .HasForeignKey("HouseId");
                });

            modelBuilder.Entity("HomeSecuritySystem.Domain.House", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
