// <auto-generated />
using HomeSecuritySystem.Persistence.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeSecuritySystem.Persistence.Migrations
{
    [DbContext(typeof(HSSDatabaseContext))]
    [Migration("20250202210911_seedDeviceData")]
    partial class seedDeviceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeSecuritySystem.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceType = "Sensor",
                            Model = "Model A",
                            Status = true,
                            UserId = "User1"
                        },
                        new
                        {
                            Id = 2,
                            DeviceType = "Camera",
                            Model = "Model B",
                            Status = false,
                            UserId = "User2"
                        },
                        new
                        {
                            Id = 3,
                            DeviceType = "Alarm",
                            Model = "Model C",
                            Status = true,
                            UserId = "User3"
                        },
                        new
                        {
                            Id = 4,
                            DeviceType = "Sensor",
                            Model = "Model D",
                            Status = true,
                            UserId = "User4"
                        },
                        new
                        {
                            Id = 5,
                            DeviceType = "Camera",
                            Model = "Model E",
                            Status = false,
                            UserId = "User5"
                        });
                });

            modelBuilder.Entity("HomeSecuritySystem.Domain.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1234 Main St",
                            City = "City",
                            Country = "Country",
                            Name = "House 1",
                            PostalCode = 12345,
                            Region = "Region"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1234 Main St",
                            City = "City",
                            Country = "Country",
                            Name = "House 2",
                            PostalCode = 12345,
                            Region = "Region"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1234 Main St",
                            City = "City",
                            Country = "Country",
                            Name = "House 3",
                            PostalCode = 12345,
                            Region = "Region"
                        },
                        new
                        {
                            Id = 4,
                            Address = "1234 Main St",
                            City = "City",
                            Country = "Country",
                            Name = "House 4",
                            PostalCode = 12345,
                            Region = "Region"
                        },
                        new
                        {
                            Id = 5,
                            Address = "1234 Main St",
                            City = "City",
                            Country = "Country",
                            Name = "House 5",
                            PostalCode = 12345,
                            Region = "Region"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
